### ISSUE TITLE
Feedback form is currently a Google Doc for Durham.  We should either update it or remove it.

### ISSUE THREAD

**Issue by carlvlewis** [opensavannah/drainsavannah.org#10]
Make a paperform.co account

**Comment by carlvlewis** [comment]
Done.

**Comment by roberth05** [comment]
The form now goes to a leadership sign up form.  We should have a form on the site that allows people to submit issues or suggestions to make it better.  @carlvlewis Can we change it?

**Comment by carlvlewis** [comment]
Fixed. Copy paste error.
