### ISSUE TITLE
Emails when adopting a drain are still referencing 311 SF

### ISSUE THREAD

**Issue by roberth05** [opensavannah/drainsavannah.org#19]
Need to change to Savannah.

**Comment by brandonmichaelhunter** [comment]
I can work on this one.

**Comment by brandonmichaelhunter** [comment]
@roberth05 do you know how I can setup email within the Ruby app?

**Comment by roberth05** [comment]
@brandonmichaelhunter set the environment variables for the service or host you are using in the .env file like is done with the DB_USER in the README.md file.

`cat MAILSERVER_HOST=smtp.XXXXX.com>>.env`

The needed variables are:
MAILSERVER_DOMAIN
MAILSERVER_HOST
MAILSERVER_PASSWORD
MAILSERVER_USERNAME

You should then be setup in your development environment.

**Comment by roberth05** [comment]
Closed with PR #25
