### ISSUE TITLE
List of adopted drains not showing as links

### ISSUE THREAD

**Issue by roberth05** [opensavannah/drainsavannah.org#26]
After logging in, the list of drains adopted by the current user are not shown as links.

**Comment by brandonmichaelhunter** [comment]
Is this still a valid issue?

**Comment by roberth05** [comment]
I still experience it.  Can you check on your machine and verify?

**Comment by brandonmichaelhunter** [comment]
Yea, its happening on my machine. Where in the code does it associated the user with a drain?

**Comment by roberth05** [comment]
The links are generated in _user_things.html.haml.

If you look at the structure in Chrome dev tools, the link is created but
the words are outside the tag.

**Comment by brandonmichaelhunter** [comment]
Ok I can take a look into this...

**Comment by roberth05** [comment]
Thank you!

**Comment by brandonmichaelhunter** [comment]
Hey guys, it appears I got this fixed. I'm going to be doing some more testing morning and once completed I'll have this checked in ready for review.

**Comment by roberth05** [comment]
Didn't resolve in live version after merge.

**Comment by roberth05** [comment]
Was a problem with the records in the DB.  Closing
