### ISSUE TITLE
Search not functioning on Safari mobile

### ISSUE THREAD

**Issue by roberth05** [opensavannah/drainsavannah.org#27]
Drains do not appear when searching for an address in Safari mobile

**Comment by brandonmichaelhunter** [comment]
I can take a look into this one.

**Comment by brandonmichaelhunter** [comment]
@roberth05 & @carlvlewis - is there anything specific that the user said about searching for working? I just tested it out on a safri and chrome browser on my IPhone 8s plus. The only issue I see is that the icons that you adopted are still gray even though you adopted them.

**Comment by carlvlewis** [comment]
I think she may have been referring to her address specifically. We should have asked her to try a different address. 

–––

We believe that local government can work by the people, for the people, in the digital age. *Help us make it so. ( https://share.polymail.io/v1/z/b/NWQ3ZGIzZDZkNzUw/OrgrAcXaqNZ4-UPA3ST7zyToTcDXkfY-qOK8g8JX0P_PNGnfUIIQACN6XHMAYFW2k7v8AhapYEZq6Jf-UkuM8bNvxxQuumYKljwczvkOXvFEdEDoTdb5CQv64ClMhM7YgsW5j0GlWzR_f5uqV0v9Ki15PPhiTPjD44S1mGnz-nTnkT1BLANkdMFSZq5UyNHNzvYXfbsKUYXfD9rMUZjsKnHte6ruCt1V1s12Pz7ldt3VD-55hhiu2-nNl4A= ) *

*Carl V. Lewis*
Fellow, Code for America
Team Savannah
+1 (912) 816-7007
2222 Bull St.
Savannah, Ga 31401

**Comment by roberth05** [comment]
We tried multiple addresses on her phone.  The search appeared to complete, but after collapsing the sidebar none of the map markers displayed.

I'll try on another phone today.  If it works there, we'll mark it closed.

**Comment by roberth05** [comment]
Checked it today on another iPhone w/ Safari.  Seemed to work ok.  It may have been a cache issue or something else with her phone.  We can check again at next meeting.
